start: statements

statements: [statement]
statement: "let" NAME "=" expr ";"
         | unary_exp "=" expr ";"
         | "fun" NAME "(" (NAME ("," NAME)*)? ")" ":" statements "END"
         | expr ";"

expr: "[" "]"
    | "[" arg_list "]"
    | "{" dict_entries "}"
    | "{" "}"
    | NAME ":" expr
    | expr "+" expr
    | expr "-" expr
    | expr "*" expr
    | expr "/" expr
    | expr "%" expr
    | expr "==" expr
    | expr "//" expr
    | expr ">" expr
    | expr "<" expr
    | expr "==" expr
    | expr ">=" expr
    | expr "<=" expr
    | expr "and" expr
    | expr "or" expr
    | expr "?" expr ":" expr
    | unary_exp
    | postfix_exp

dict_entries: dict_entry ("," dict_entry)*

dict_entry: NAME ":" expr

unary_exp: "NOT" expr
         | "-" unary_exp
         | "+" unary_exp
         | "~" unary_exp
         | postfix_exp

postfix_exp: primary_exp
           | postfix_exp "(" arg_list ")"
           | postfix_exp "(" ")"
           | postfix_exp "[" expr "]"
           | postfix_exp "." NAME

primary_exp: "(" expr ")"
           | STRING
           | NAME
           | const

arg_list: expr ("," expr)*

const: NUMBER

NAME: /[a-zA-Z_][a-zA-Z_0-9]*/
%import common.ESCAPED_STRING   -> STRING
%import common.SIGNED_NUMBER    -> NUMBER
